spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver   # 使用mysql驱动
    #driver-class-name: com.mysql.jdbc.jdbc2.optional.MysqlXADataSource
    #driver-class-name: net.sf.log4jdbc.DriverSpy  # 使用 log4jdbc sql日志会携带参数
   # type: com.alibaba.druid.pool.DruidDataSource
    type: com.alibaba.druid.pool.xa.DruidXADataSource

    # 主库
    master:
      url: jdbc:mysql://10.130.0.37:3307/jwwl_attachment?useUnicode=true&characterEncoding=UTF-8&pinGlobalTxToPhysicalConnection=true
     # url: jdbc:log4jdbc:mysql://10.130.0.37:3307/jwwl_attachment?useUnicode=true&characterEncoding=utf8
      username: root
      password: 123456

    # 从库1数据源
    slave1:
      url: jdbc:mysql://10.130.0.37:3306/jwwl_attachment?useUnicode=true&characterEncoding=UTF-8&pinGlobalTxToPhysicalConnection=true
      #url: jdbc:log4jdbc:mysql://10.130.0.37:3306/jwwl_attachment?useUnicode=true&characterEncoding=utf8
      username: root
      password: 123456

    # 从库2数据源
    slave2:
      url: jdbc:mysql://10.130.0.37:3306/jwwl_attachment?useUnicode=true&characterEncoding=UTF-8&pinGlobalTxToPhysicalConnection=true
      #url: jdbc:log4jdbc:mysql://10.130.0.37:3306/jwwl_attachment?useUnicode=true&characterEncoding=utf8
      username: root
      password: 123456

    # 连接池的配置信息
    # 初始化大小，最小，最大
    initialSize: 8
    minIdle: 5
    maxActive: 20
    poolSize: 10  # 连接池里面连接的个数
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 30000
    # 事物超时时间
    transactionTimeout: 10000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,slf4j
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    stat-view-servlet:
      allow: 127.0.0.1  # IP 白名单
      deny: 192.168.0.10 #  IP黑名单(共同存在时，deny优先于allow)
      enabled: true
      login-password: admin  # 控制台用户名和密码
      login-username: admin
      reset-enable: false
    web-stat-filter:
      enabled: true
      exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'
    # 合并多个DruidDataSource的监控数据
    useGlobalDataSourceStat: true


  jpa.:
    database: mysql
    generate-ddl: true
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: none
      # update：表示自动根据model对象来更新表结构，启动 hibernate 时会自动检查数据库，如果缺少表则自动建表；缺少列则自动添加列；
      # create： 启动hibernate时，自动删除原来的表，新建所有的表，所以每次启动后的以前数据都会丢失。
      # create-drop：应用停下来的时候，自动会把表和数据删掉、
      # none： 什么也不做；
      # validate：会验证类里的属性和表字段是否一致，不一致，则会报错；
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy

  #jta:
    #transaction-manager-id: transactionManager
    #bitronix:
      #datasource:
        #allow-local-transactions: true # 事务管理器是否应允许混合XA和非XA事务
    #atomikos:
      #datasource:
        #borrow-connection-timeout: 30  #从池借用连接的超时（以秒为单位）
        #max-idle-time: 60  #从池中清除连接的时间（以秒为单位）
        #maintenance-interval: 60 # 池维护线程运行之间的时间（以秒为单位）
        #reap-timeout: 20
        #max-pool-size: 30
      #properties:
        #max-actives: 50
        #max-timeout: 300000ms
        #default-jta-timeout: 10000ms
        #enable-logging: true



  jta:
    enabled: true
    service: com.atomikos.icatch.standalone.UserTransactionServiceFactory
    max-actives: 200
    enable-logging: false
    transaction-manager-id: transactionManager
    bitronix:
      datasource:
        allow-local-transactions: true # 事务管理器是否应允许混合XA和非XA事务
    atomikos:
      datasource:
        one:
          unique-resource-name: dataSourceOne
          max-pool-size: 5
          min-pool-size: 1
          max-life-time: 20000
          borrow-connection-timeout: 10000
          xa-data-source-class-name: com.mysql.jdbc.jdbc2.optional.MysqlXADataSource
          testQuery: SELECT 1 FROM DUAL
          xa-properties:
            user: root
            password: root
            URL: jdbc:mysql://10.130.0.37:3306/jwwl_attachment?useUnicode=true&characterEncoding=UTF-8&pinGlobalTxToPhysicalConnection=true

        two:
          unique-resource-name: dataSourceTwo
          max-pool-size: 5
          min-pool-size: 1
          max-life-time: 20000
          borrow-connection-timeout: 10000
          xa-data-source-class-name: com.mysql.jdbc.jdbc2.optional.MysqlXADataSource
          testQuery: SELECT 1 FROM DUAL
          xa-properties:
            user: root
            password: 123456
            URL: jdbc:mysql://10.130.0.37:3307/jwwl_attachment?useUnicode=true&characterEncoding=UTF-8&pinGlobalTxToPhysicalConnection=true

        three:
          unique-resource-name: dataSourceThree
          max-pool-size: 5
          min-pool-size: 1
          max-life-time: 20000
          borrow-connection-timeout: 10000
          xa-data-source-class-name: com.mysql.jdbc.jdbc2.optional.MysqlXADataSource
          testQuery: SELECT 1 FROM DUAL
          xa-properties:
            user: root
            password: 123456
            URL: jdbc:mysql://10.130.0.37:3307/jwwl_attachment?useUnicode=true&characterEncoding=UTF-8&pinGlobalTxToPhysicalConnection=true